### ISSUE TITLE
Unable to translate app remains same language

### ISSUE THREAD

**Issue by joshuachua352** [Approved233/MapleStoryM-Translate#1]
When i extract the three files to a rar file and name to data.bin.lan.kor.tbl as archive and bring to android/data/com.nexon.nsc.maplem/files/assetdata and place here with the exact files name and archive contents all there it doesnt patch the maple m showing no translation at all after i reopen the app.how do i solve this thanks in advance?

**Comment by Approved233** [comment]
Please go to the [release](https://github.com/Approved233/MapleStoryM-Translate/releases) page
Download latest .tbl file **(not source code)**
